In [3]:
import torch

# Check if GPU is available
if torch.cuda.is_available():
    print("GPU is available and PyTorch is using it.")
    
    # Get the current device (should be GPU)
    device = torch.device("cuda")
    
    # Print GPU details
    print(f"Device: {device}")
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / (1024 ** 3):.2f} GB")
    print(f"CUDA Version: {torch.version.cuda}")
else:
    print("GPU is not available. PyTorch is using the CPU.")

GPU is available and PyTorch is using it.
Device: cuda
GPU Name: NVIDIA GeForce GTX 1650
GPU Memory: 4.00 GB
CUDA Version: 12.4


In [4]:
!nvidia-smi

Mon Nov 25 06:30:05 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.51.01              Driver Version: 565.90         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8              5W /   75W |     542MiB /   4096MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
print(torch.__version__)

2.5.1+cu124


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Introduction to Tensors

### Creating tensors  

In [8]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [11]:
scaler.ndim 

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

In [13]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [17]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors  

Why random tensors?  

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [27]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4858, 0.5591, 0.1311, 0.8349],
        [0.8560, 0.9560, 0.2058, 0.3888],
        [0.5974, 0.2569, 0.9101, 0.2340]])

In [28]:
random_tensor.ndim

2

In [30]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [32]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [42]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes  
**Note:** Tensor datatype is one of the 3 big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [53]:
float_32_tensor.dtype

torch.float32

In [54]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)